version: '3'

services:
  master:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - PG_HOST=10.10.10.160
      - PG_DATABASE=postgres
      - PG_PORT=5000
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_WRITE_PORT=5001
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master  -L DEBUG -H http://master:8089
  
  worker:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - PG_HOST=10.10.10.160
      - PG_DATABASE=postgres
      - PG_PORT=5000
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_WRITE_PORT=5001
    deploy:
      mode: replicated
      replicas: 1

    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker -L DEBUG --master-host master
